# Generated by Django 4.1.3 on 2023-01-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "bank_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="銀行id",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=30, unique=True, verbose_name="銀行名"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Bank",},
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "bank_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="loan_app.bank",
                        verbose_name="銀行id",
                    ),
                ),
                ("floating", models.FloatField(default=0.0, verbose_name="変動金利型")),
                ("fixed_1", models.FloatField(default=0.0, verbose_name="固定金利選択型01年")),
                ("fixed_2", models.FloatField(default=0.0, verbose_name="固定金利選択型02年")),
                ("fixed_3", models.FloatField(default=0.0, verbose_name="固定金利選択型05年")),
                ("fixed_5", models.FloatField(default=0.0, verbose_name="固定金利選択型05年")),
                ("fixed_7", models.FloatField(default=0.0, verbose_name="固定金利選択型07年")),
                ("fixed_10", models.FloatField(default=0.0, verbose_name="固定金利選択型10年")),
                ("fixed_15", models.FloatField(default=0.0, verbose_name="固定金利選択型15年")),
                ("fixed_20", models.FloatField(default=0.0, verbose_name="固定金利選択型20年")),
                ("fixed_30", models.FloatField(default=0.0, verbose_name="固定金利選択型30年")),
                (
                    "fix_10to15",
                    models.FloatField(default=0.0, verbose_name="全期間固定金利型11〜15年"),
                ),
                (
                    "fix_15to20",
                    models.FloatField(default=0.0, verbose_name="全期間固定金利型16〜20年"),
                ),
                (
                    "fix_20to25",
                    models.FloatField(default=0.0, verbose_name="全期間固定金利型21〜25年"),
                ),
                (
                    "fix_25to30",
                    models.FloatField(default=0.0, verbose_name="全期間固定金利型26〜30年"),
                ),
                (
                    "fix_30to35",
                    models.FloatField(default=0.0, verbose_name="全期間固定金利型31〜35年"),
                ),
            ],
            options={"verbose_name_plural": "InterestRate",},
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "option_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="オプションid",
                    ),
                ),
                ("option_name", models.CharField(max_length=30, verbose_name="オプション名")),
                ("option_rate", models.FloatField(default=0.0, verbose_name="優遇金利")),
                ("option_ex", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
                (
                    "bank_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_app.bank",
                        verbose_name="銀行id",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Option",},
        ),
    ]
