# Generated by Django 4.1.3 on 2022-12-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0002_bank_option_delete_post_interestrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestrate",
            name="bank_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="loan_app.bank",
                verbose_name="銀行id",
            ),
        ),
    ]
