# Generated by Django 4.1.3 on 2023-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0003_alter_bank_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank_name",
            field=models.CharField(max_length=30, verbose_name="銀行名"),
        ),
    ]
