# Generated by Django 4.1.3 on 2022-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0004_alter_interestrate_fixed_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="interestrate", options={},),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_1",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_10",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_15",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_2",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_20",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_3",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_30",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_5",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_7",
            field=models.FloatField(default=0.0, verbose_name=""),
        ),
    ]
