# Generated by Django 4.1.3 on 2023-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0004_alter_bank_bank_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.UniqueConstraint(
                fields=("bank_name", "user_id"), name="bank_name_unique"
            ),
        ),
    ]
