# Generated by Django 4.1.3 on 2023-01-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0005_bank_bank_name_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("bank_id", "option_name"), name="option_name_unique"
            ),
        ),
    ]
