# Generated by Django 4.1.3 on 2023-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0006_option_option_name_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestrate",
            name="fix_10to15",
            field=models.FloatField(verbose_name="全期間固定金利型11〜15年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fix_15to20",
            field=models.FloatField(verbose_name="全期間固定金利型16〜20年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fix_20to25",
            field=models.FloatField(verbose_name="全期間固定金利型21〜25年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fix_25to30",
            field=models.FloatField(verbose_name="全期間固定金利型26〜30年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fix_30to35",
            field=models.FloatField(verbose_name="全期間固定金利型31〜35年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_1",
            field=models.FloatField(verbose_name="固定金利選択型01年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_10",
            field=models.FloatField(verbose_name="固定金利選択型10年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_15",
            field=models.FloatField(verbose_name="固定金利選択型15年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_2",
            field=models.FloatField(verbose_name="固定金利選択型02年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_20",
            field=models.FloatField(verbose_name="固定金利選択型20年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_3",
            field=models.FloatField(verbose_name="固定金利選択型03年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_30",
            field=models.FloatField(verbose_name="固定金利選択型30年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_5",
            field=models.FloatField(verbose_name="固定金利選択型05年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="fixed_7",
            field=models.FloatField(verbose_name="固定金利選択型07年"),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="floating",
            field=models.FloatField(verbose_name="変動金利型"),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_rate",
            field=models.FloatField(verbose_name="優遇金利"),
        ),
    ]
