# Generated by Django 4.1.3 on 2023-01-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0007_alter_interestrate_fix_10to15_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="option", name="option_ex",),
    ]
