# Generated by Django 4.1.3 on 2023-01-22 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0008_remove_option_option_ex"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestrate",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="作成日時",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interestrate",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
