# Generated by Django 4.1.3 on 2023-01-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan_app", "0009_interestrate_created_at_interestrate_updated_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="interestrate", name="created_at",),
    ]
